# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'Akos_Sonarqube_in_Azure_VM'
    scannerMode: 'MSBuild'
    msBuildVersion: '9.0.0.100868'
    projectKey: 'sonar:Akos_Azure'
    projectName: 'Akos_Azure'

- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go (ed55859d-6439-42f0-be22-92f432bd587a)'
    command: 'build'

    
- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

